[package]
name = "bb-core"
version = "0.2.0"
edition = "2021"
license = "MIT"

[dependencies]
chrono = "0.4.45"
nvml-wrapper = "0.13.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }
sysinfo = "0.39.6"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Performance", "Win32_System_Power", "Win32_System_Threading"] }

